syrupy-project/syrupy

.githooks.ini, setup.py, src/syrupy/__init__.py, src/syrupy/assertion.py, src/syrupy/io.py, src/syrupy/plugins/image/__init__.py, src/syrupy/plugins/image/io.py, src/syrupy/serializer.py, src/syrupy/session.py, src/syrupy/types.py, tasks.py, tests/__snapshots__/test_snapshots.yaml, tests/test_injection.py, tests/test_snapshots.py
- `inv test` should show unused snapshots in single file
- Comment out the `assert actual == snapshot_png` line in the image plugin test
https://github.com/tophat/syrupy/blob/1ad07661f3842557d1553c74f6b7976a7f8d81ef/tests/test_image_plugin.py#L22
- `inv test` should show that the image file is also unused
- `inv test -u` should update the snapshot files and remove the image snapshot file
- `inv test` should show no snapshot file is unused
- Comment out all the assertions in the `test_snapshot.py` file
- `inv test -u` should delete the `test_snapshot.yaml` file
- This does not fail if there are unmatched snapshots but I think that should be a separate feature #13
=> feat: remove unused snapshots in snapshot file

setup.py
Previously we only exported "syrupy" and not "syrupy.plugins". This change will export all of "syrupy".
=> Export entire syrupy module

src/syrupy/assertion.py, src/syrupy/io.py, src/syrupy/serializer.py, tests/__snapshots__/test_snapshots.yaml, tests/test_snapshots.py
=> fix: compare snapshots without deserializing

mypy.ini, src/syrupy/__init__.py, src/syrupy/assertion.py, src/syrupy/plugins/image/serializer.py, src/syrupy/serializer.py, src/syrupy/session.py, src/syrupy/terminal.py, src/syrupy/types.py, stubs/pytest.pyi, tasks.py
Uses forward references where possible. If we drop support for python 3.6, we can use implicit forward references via a future import. I think it's worth keeping 3.6 for now.
=> style: add strict typing

CHANGELOG.md, README.md, src/syrupy/__init__.py, src/syrupy/session.py, tasks.py
I like "update-snapshots", however if this makes it easier to adopt, it's a minor point.
=> feat: change update opt to conform to snapshot test, close #29

dev-requirements.in, dev-requirements.txt, pyproject.toml, tasks.py
Do not count
- Function definition lines
- Function wrappers
- if TYPE_CHECKING
- Import lines
=> chore: do not report on implicitly covered lines

src/syrupy/serializers/base.py, src/syrupy/serializers/raw_single.py, src/syrupy/serializers/yaml.py, src/syrupy/session.py, tests/__snapshots__/test_snapshots.yaml, tests/test_plugin_custom.py, tests/test_snapshots.py
The bug this fixes:
Adding
```
def test_multiline(snapshot):
assert "multi\nline" == snapshot
```
to its own test file and running `inv test -u` would create a corrupted file.
=> fix: yaml multiline string should be read successfully

CONTRIBUTING.md, README.md, src/syrupy/__init__.py, src/syrupy/constants.py, src/syrupy/session.py, tests/test_integration.py, tests/test_single_serializer.py
Makes syrupy fail test session on unused snapshots.
Adds a flag `--snapshot-warn-unused` which can be used to allow warnings.
- Closes #13 
=> feat: fail unused snapshots

setup.py, src/syrupy/assertion.py, src/syrupy/data.py
We were missing the attrs dependency while relying on attrs>=19.2.0.
This PR adds the dependency to the setup.py and makes some minor changes so we're compatible with attrs==18.2.0.
=> fix: declare attrs dependency

setup.py
This PR defines explicit version ranges for the required dependencies, making the assumption that the dependencies follow semantic versioning (or at the minimum, won't release breaking changes without a major version bump).
We do not test in CI with old dependencies -- this wouldn't be feasible. I tested the minimum versions by installing the min. versions locally and running `inv test`.
=> chore: explicit version ranges for required deps

CHANGELOG.md, README.md, setup.py, src/syrupy/assertion.py, src/syrupy/extensions/base.py, src/syrupy/extensions/single_file.py, src/syrupy/location.py, tests/__snapshots__/test_extension_amber.ambr, tests/examples/test_custom_snapshot_directory.py, tests/test_extension_amber.py
Refactors base extension to remove subdirectory prop.
Bumps the python package to beta.
- Closes #89 
- Closes #98 
=> fix: support nested classes

CHANGELOG.md, README.md, src/syrupy/extensions/amber.py, tests/__snapshots__/test_extension_amber.ambr, tests/examples/__snapshots__/test_custom_object_repr.ambr, tests/examples/test_custom_object_repr.py, tests/test_extension_amber.py
Adds a default serialization for custom objects
N/A
Makes adoption easier
=> feat: default serialization for custom objects

CHANGELOG.md, src/syrupy/extensions/amber.py, tests/__snapshots__/test_extension_amber.ambr, tests/__snapshots__/test_integration_default.ambr, tests/test_extension_amber.py
Always sorts serialized values
- Closes #102
N/A
=> fix: allow hashable types to be used as dictionary keys

CHANGELOG.md, src/syrupy/extensions/amber.py, tests/__snapshots__/test_extension_amber.ambr, tests/examples/__snapshots__/test_custom_object_repr.ambr
Adds support for named tuple fields
Add trailing commas to class fields
- Closes #106
N/A
=> feat: update serialization to support named tuple fields

CHANGELOG.md, src/syrupy/extensions/amber.py, tests/__snapshots__/test_extension_amber.ambr, tests/test_extension_amber.py
If a carriage return is present in a string, Syrupy will strip out the carriage return when serializing the data thus making the assertion persistently fail even after a snapshot-update.
This PR keeps the original newlines by explicitly setting the amber newlines arg of `open`.
- Closes #113
This does not fix the assertion reporter. With this PR, if you remove the `\r` from one of the assertions in the added test, you will get an extremely unhelpful diff of "...".
=> fix: serialize carriage returns, #113

README.md
Corrects some typos and clarifies language in the README.
=> docs: fix typos, and clarify language

CHANGELOG.md, src/syrupy/__init__.py, src/syrupy/extensions/base.py, src/syrupy/report.py, src/syrupy/session.py, src/syrupy/utils.py, tests/test_integration_default.py
This PR adds some handling around filenames that can be passed to `pytest` to target testfiles. Previously, passing in file paths would run the tests on these paths, and consider snapshots that weren't touched as unused -- even though they were actually used by other tests not targeted by `pytest` in that instance.
By passing down a list of targeted files and using a filtering function, this takes out snapshots that aren't related to the targeted files, if `pytest` is passed some paths. This way, `syrupy` no longer purges snapshots by mistake.
This addresses #119.
=> Ensure that untouched snapshots are not deleted in targeting mode

CHANGELOG.md, src/syrupy/__init__.py, src/syrupy/data.py, src/syrupy/extensions/base.py, src/syrupy/extensions/single_file.py, src/syrupy/location.py, src/syrupy/report.py, tests/examples/test_custom_snapshot_directory.py, tests/test_integration_custom.py, tests/test_integration_default.py
- Fixes issue where snapshot files were not cleaned up when running specific test files
- Fixes issue where targeting specific test nodes in a test file was not supported
- Fixes issue where targeting specific test modules using pyargs was not supported
N/A
=> Fix cleanup unused snapshots when targeting files

CHANGELOG.md, CONTRIBUTING.md, src/syrupy/extensions/amber.py, src/syrupy/extensions/base.py, src/syrupy/extensions/single_file.py, src/syrupy/location.py, src/syrupy/report.py, src/syrupy/session.py, src/syrupy/utils.py, tests/examples/test_custom_snapshot_directory.py, tests/test_extension_single_file.py, tests/test_integration_default.py, tests/test_utils.py
As explained in #121, `pathlib` is the newer, py3 successor to `os.path` and provides an arguably friendlier interface to system paths than `os.path` does. Additionally, it is built to be platform agnostic, which is a hoot.
This resolves #121 and replaces all instances of `os.path` with `pathlib.Path` methods. This encompasses both the source and the test code.
**Since the changes are entirely internal, this doesn't add any more tests (all present tests passing is sufficient to establish correctness and equivalency to the previous `os.path` patterns).**
- ~[ ] This PR has sufficient test coverage.~
- ~[ ] I have updated the CHANGELOG.md.~
=> Replace all instances of `os.path` with `pathlib` calls

CHANGELOG.md, src/syrupy/location.py, src/syrupy/report.py, tests/test_integration_default.py
Check if test node is in snapshot name when the test node is a valid identifier else check if the snapshot name is in the test node. This allows expanded tests like `test_parametrized` match `test_parametrized[a]` and `test_parametrized[b]`.
- Closes #134
N/A
=> Fix faulty matching test node to snapshot name

CHANGELOG.md, src/syrupy/__init__.py, src/syrupy/assertion.py, src/syrupy/data.py, src/syrupy/location.py, src/syrupy/report.py, src/syrupy/session.py, tests/test_integration_default.py
Filters out unused snapshots when selecting tests nodes.
- Closes #138 
=> Filter out unused snapshots when selecting test nodes

CHANGELOG.md, src/syrupy/__init__.py, src/syrupy/report.py, tests/__snapshots__/test_integration_default.ambr, tests/test_integration_default.py
Moves syrupy snapshot reporting to proper location
- Closes #142 
=> Show snapshot report after failing tests

src/syrupy/extensions/base.py, src/syrupy/location.py
Fixes snapshot name warning showing up incorrectly on snapshot creation.
**STR**
- `git checkout master`
- `rm */**.ambr`
- `pytest --snapshot-update`
- See warnings
**FIX**
- `git checkout fix-warning`
- `rm */**.ambr`
- `pytest --snapshot-update`
- No warnings
=> fix: snapshot name warning showing on false negatives

setup.py
Specifies correct min version of pytest
- `pip install -U pytest==5.0.0`
- `pytest`
- **See failure**
- `pip install -U pytest==5.1.0`
- `pytest`
- **See success**
- Closes #156 
=> fix: specify correct min version of pytest

src/syrupy/location.py, tests/test_integration_default.py
Fixes a bug where targeting a specific subset of tests in a test class would incorrectly report the non-targeted test cases as "unused".
=> fix: correctly track unused snapshots in classes

README.md
Adds simple copy/paste bash script to migrate from snapshottest.
- Closes #155, update migration instructions for developers coming from snapshottest.
I considered a post-install script, however the overhead seems unnecessary when this is targeting only first time users (and a subset at that).
=> docs(readme): include migration script, close #155

src/syrupy/location.py, tests/test_integration_default.py
This fixes a regression introduced in #177 around generating parsed names from snapshot names with index suffixes.
- #177
=> fix: Fix parsing identifiers from snapshot names

src/syrupy/location.py, tests/test_integration_default.py
See: https://github.com/tophat/syrupy/pull/186
Author: https://github.com/taion
=> fix: parsing identifiers from snapshot names (#186)

src/syrupy/assertion.py, tests/test_integration_single_file.py
Prints out the snapshot that will be created when it does not exist
- Closes #184 
=> fix: show snapshot data in report when does not exist

src/syrupy/extensions/amber.py, tests/__snapshots__/test_extension_amber.ambr, tests/test_extension_amber.py
Indents multiline strings only when the parent itself is indented, this is to keep snapshots of multiline strings that are not nested in any data structure, simple.
- Closes #193, multiline strings should be indented according to parent
=> feat(amber): indent multiline strings, close #193

src/syrupy/location.py, tests/__snapshots__/test_extension_amber.ambr, tests/test_extension_amber.py
Use the pytest node location to parse the full class name path
- Closes #195
=> fix: use the test node location when determining snapshot class name

src/syrupy/extensions/amber.py, tests/__snapshots__/test_extension_amber.ambr, tests/test_extension_amber.py
v0.4.0 contains some breaking changes to the amber snapshot serializer.
- Closes #183, removes added trailing whitespace from multiline string
- Closes #193, multiline strings should be indented according to parent
=> feat: v0.4.0 - Amber serializer changes

src/syrupy/extensions/amber.py
Specifies what encoding to use when reading and writing snapshots to amber fossils
- Closes #196
- Unable to test atm
=> fix: specify encoding when reading and writing amber fossils

src/syrupy/location.py, stubs/pytest.pyi, tests/__snapshots__/test_extension_amber.ambr, tests/test_extension_amber.py
This fixes a regression from https://github.com/tophat/syrupy/pull/197 for tests with parameters with dots in them.
https://github.com/tophat/syrupy/pull/197, sorta
Without this change, the dotted parameter name would confuse the earlier iteration of the `classname` logic.
=> fix: Handle dotted parameters in classname

script/bootstrap
Since the bootstrap script is meant to be sourced (`. script/bootstrap`) rather than executed (`./script/bootstrap`), the shebang is a bit misleading.
N/A
Just noticed this because I adopted the `scripts/` pattern in a recent project and used your scripts as a starting point.
Thanks for the great project, btw.
=> chore: remove unnecessary shebang from script

setup.py
The project supports any Python 3.6+ version, so we need to reflect this in `setup.py`.
- Closes #238: Python version in setup.py is outdated
=> Update setup.py, so that it allows for any Python 3.6+ version to be used

README.md, src/syrupy/filters.py, tests/__snapshots__/test_filters.ambr, tests/test_filters.py
Add simple prop filter factory helper
N/A
=> feat: add simple props filter helper

dev_requirements.txt, setup.py
This widens the dependency range for pytest in `setup.py`, which allows me to upgrade to pytest v6.x without pip-tools complaining at me.
None of the breaking changes are relevant, as far as I can tell. I can run pytest v6 together with Syrupy without obvious problems.
=> chore: Mark compatibility with pytest v6.x

README.md
Force a version release with changelog entry. Previously used the wrong semantic prefix.
=> fix: support pytest v6

src/syrupy/__init__.py, src/syrupy/report.py, src/syrupy/session.py
Interrupting a test run leads to syrupy assuming all selected but untouched snapshots are unused and should be marked as candidates for deletion.
**Before**
**After**
- Needs some way to test this
=> fix: only perform session finish on test items actually ran

src/syrupy/assertion.py, tests/syrupy/extensions/amber/test_amber_matchers.py
=> fix: assertion exception shows error at correct location

src/syrupy/__init__.py, src/syrupy/location.py, src/syrupy/report.py, src/syrupy/session.py
- Removes unnecessary use of dict in the session/report for tracking all test items
- Renames ran items to selected items, just more semantically accurate
- Move test collection logic into the session instance
=> refactor: optimise session data structures

setup.py
This follows PEP-561 to mark syrupy as compatible with type
checking (driven by the type annotations that already exist and are
checked), by creating an empty `py.typed` in the project. This stops
users from having to ignore syrupy when type checking, and allows the
type checker to provide specific guidance about possible problems.
See https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages for more information about this approach.
- Closes #439, discussing the value for type checking
=> feat: add PEP-561 py.typed file for downstream type checkers

src/syrupy/__init__.py, src/syrupy/report.py, src/syrupy/session.py, tests/integration/test_snapshot_option_update.py
Correct usage of pytest invocation arguments
```sh
$ pytest --ff tests/syrupy/extensions/amber/test_amber_serializer.py
===================================== test session starts ======================================
platform darwin -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/Emmanuel/Sources/github/tophat/syrupy, configfile: pyproject.toml
plugins: syrupy-2021.5.31.224541039469
collected 57 items                                                                             
run-last-failure: no previously failed tests, not deselecting items.
tests/syrupy/extensions/amber/test_amber_serializer.py ................................. [ 57%]
........................                                                                 [100%] …
```
=> fix(report): correctly use pytest invocation arguments

conftest.py, src/syrupy/assertion.py, src/syrupy/extensions/amber/__init__.py, src/syrupy/extensions/amber/serializer.py, src/syrupy/filters.py, src/syrupy/matchers.py, src/syrupy/types.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_serializer.ambr, tests/syrupy/extensions/amber/test_amber_serializer.py
* Improves the typing of `PropertyMatcher` and `PropertyFilter`
* Makes `DataSerializer` methods explicit about accepted types
=> feat(types): explicit property matcher and filter types kwargs

README.md, src/syrupy/matchers.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_matchers.ambr, tests/syrupy/extensions/amber/test_amber_matchers.py
Adds a `regex` flag to the path_type matcher.
- Closes #423
=> feat: support regex path type matching

src/syrupy/report.py, tasks/test.py, tests/integration/test_snapshot_similar_names_default.py, tests/integration/test_snapshot_similar_names_file_extension.py
=> fix: unused snapshot not filtered out when specific node

src/syrupy/extensions/amber/serializer.py
This applies the `functools.lru_cache` memoising decorator to the low level `amber.DataSerializer.read_file` method, which dramatically improves performance by avoiding re-reading a single snapshot file dozens of times, thus eliminating the quadratic behaviour observed in #539 in the common case of read-only interaction with amber snapshots.
For the test in #539, with a single snapshot test parametrised with `SIZE` instances (note that doubling the size now doubles the time):
| SIZE | before (1.43) time (s) | after (this PR) time (s) |
|---|---|---|
| 100 | 0.09 | 0.07 | 
| 500 | 0.75 | 0.29 |
| 1000 | 2.42 | 0.51 |
| 2000 | 8.24 | 0.98 |
| 10000 | 201 | 4.64 |
For our real-world test suite, with 453 snapshots across 25 files:
| syrupy version | time (s) |
|---|---|
| 1.4.1 (original) | …
=> perf: memoise DataSerializer.read_file results

src/syrupy/session.py
Only set the ran items if there is a corresponding selected item.
- Closes #451
Need to give this more thought on how to test it to prevent a regression. Open to ideas.
=> fix: filter ran items using selected items, close #451

src/syrupy/extensions/json/__init__.py
* fixed 2 additional instances
Finishes fixing using syrupy with Python 3.7
#586
=> fix(json): Use additional forward references for py3.7

poetry.lock, pyproject.toml, src/syrupy/assertion.py, src/syrupy/data.py, src/syrupy/extensions/base.py, src/syrupy/location.py, src/syrupy/report.py, src/syrupy/session.py
Replace attrs with dataclasses + backport for py3.6. In an effort to reduce dependencies.
=> refactor: migrate from attrs to dataclasses

README.md, src/syrupy/assertion.py, src/syrupy/extensions/amber/serializer.py, src/syrupy/extensions/base.py, src/syrupy/extensions/single_file.py, src/syrupy/types.py, src/syrupy/utils.py, tests/examples/test_custom_snapshot_name.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_snapshot_diff.ambr, tests/syrupy/extensions/amber/test_amber_snapshot_diff.py
Adds snapshot naming and diffing support to promote committing short focused snapshot assertions.
- Closes #161, snapshot diffing.
Review the diff representation
=> feat: add snapshot diffing support

pyproject.toml, script/bootstrap, src/syrupy/location.py, tests/syrupy/__snapshots__/test_doctest.ambr, tests/syrupy/test_doctest.py, tests/syrupy/test_doctest.txt
Handles snapshotting in doc tests.
* Enable running doc tests in syrupy ci
* Update bootstrap script to source new venv
- From #451, error in report generation when running doctests.
* https://docs.python.org/3/library/doctest.html#doctest-objects
* https://docs.pytest.org/en/6.2.x/doctest.html
=> feat: support snapshots in doc tests

src/syrupy/assertion.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_serializer.ambr, tests/syrupy/extensions/amber/test_amber_serializer.py, tests/syrupy/extensions/json/__snapshots__/test_json_serializer/test_reflection.json
Provides representation for current snapshot assertion
- Closes #572, provide __repr__ for `SnapshotAssertion`.
=> feat: provide __repr__ for SnapshotAssertion

src/syrupy/location.py, tests/integration/test_snapshot_similar_names_default.py, tests/integration/test_snapshot_similar_names_file_extension.py, tests/syrupy/test_location.py
This fixes #596 by making the filename vs. snapshot location matching stricter: instead of allowing a filename of `test_file` to match if it's a substring of the location (e.g. `FOOtest_fileBAR` would match), it now only matches if either of these are true:
- the filename exactly matches, ignoring the extension (e.g. `test_file.ambr` matches, while `test_file_whatever.ambr` does not)
- the parent directory exactly matches (e.g. `.../test_file/foo.bar` matches, but `.../test_file.foo/bar` does not, nor `.../test_file/subdirectory/foo.bar`)
I've added tests for this, as well as expanding the existing ones for #529 to include checking test names that have matching suffices (especially relevant for `tests/integration/test_snapshot_similar_names_file_extension.py`, with the single file …
=> fix: ignore test_a_suffix snapshots when running test_a

src/syrupy/report.py, tests/integration/test_snapshot_outside_directory.py
This makes the formatting code for the unused snapshots less strict, to stop the detailed reporting (e.g. `--snapshot-details` or `--snapshot-update`) crashing when there's unused snapshots in a directory that's outside the main pytest session root directory.
The display is less good when this comes up, since it's the full path, rather than trimmed to a more relevant section, but it's better than crashing entirely!
- Closes #620
=> fix: avoid reporting crash for snapshot dir outside pytest dir

src/syrupy/terminal.py, tests/syrupy/test_terminal.py
Only call colored functions (that instantiate colored objects under the hood) if colors have been enabled.
- Closes #633, by allowing users to bypass `colored` issues by disabling colors.
Not sure about whether/where to add tests to cover the change in behavior, happy to recieve suggestions.
=> Only instantiate colored objects if color is not disabled

README.md
I think they were missing the word "Image".
=> Update names of image snapshot extension classes

CONTRIBUTING.md, src/syrupy/assertion.py, src/syrupy/constants.py, src/syrupy/data.py, src/syrupy/extensions/amber/__init__.py, src/syrupy/extensions/amber/serializer.py, src/syrupy/extensions/base.py, src/syrupy/extensions/image.py, src/syrupy/extensions/json/__init__.py, src/syrupy/extensions/single_file.py, src/syrupy/location.py, src/syrupy/report.py, src/syrupy/session.py, tests/examples/test_custom_image_extension.py, tests/examples/test_custom_snapshot_directory.py, tests/examples/test_custom_snapshot_directory_2.py, tests/examples/test_custom_snapshot_name.py, tests/integration/test_snapshot_option_update.py, tests/integration/test_snapshot_outside_directory.py, tests/integration/test_snapshot_use_extension.py, tests/syrupy/extensions/test_single_file.py, tests/syrupy/test_location.py
This PR fixes the write perf regression in syrupy v4 prerelease. As part of the refactoring necessary to fix write perf for batch writes, I ended up simplifying some of the APIs. There are a number of breaking changes, from:
- renaming SnapshotFossil to SnapshotCollection
- changing properties to methods or variables
- adding test_location as a param to a bunch of methods
- changing instance methods to classmethods (ultimately to make write_snapshot static)
- removal of pre/post read/write hooks (if someone has a valid use case, we can add it back -- it semantically changed when we shifted to batch writes anyway)
=> refactor: write performance improvements, api clarity

poetry.lock, pyproject.toml, src/syrupy/__init__.py
Addresses https://github.com/tophat/syrupy/issues/535#issuecomment-950893723 by ensuring the default extension pytest option is serializable.
=> fix: ensure all pytest options are serializable

README.md, src/syrupy/extensions/base.py, src/syrupy/report.py, src/syrupy/session.py, src/syrupy/utils.py
NOTE: When pytest-xdist is detected, we do not remove unused snapshots, since that requires coordination between the workers and the controller. A disclaimer has been added to the README and TODO comments added to the source code to help solve this problem at some point.
Related: #535
=> fix: improve pytest-xdist compatibility

README.md, src/syrupy/__init__.py, src/syrupy/report.py, src/syrupy/session.py, src/syrupy/utils.py
https://github.com/tophat/syrupy/issues/535
=> pytest-xdist compatibility improvements

src/syrupy/extensions/amber/__init__.py, src/syrupy/extensions/amber/serializer.py, tests/syrupy/__snapshots__/test_doctest.ambr, tests/syrupy/extensions/amber/__snapshots__/test_amber_serializer.ambr, tests/syrupy/extensions/amber_sorted/__snapshots__/test_amber_sort.ambr, tests/syrupy/extensions/amber_sorted/test_amber_sort.py
Supports addressing https://github.com/tophat/syrupy/issues/657 using a custom amber class until we figure out a more performant solution.
=> feat: support overriding the amber serializer class

src/syrupy/__init__.py, src/syrupy/utils.py, tests/integration/test_snapshot_option_extension.py, tests/integration/test_snapshot_option_extension_pythonpath.py
Fixes unable to use pytest's `pythonpath` option with this project's `--snapshot-default-extension` option. 
Does cause extension import errors to raise later than CLI argument parsing, and therefore emit on stdout, instead of stderr.
Also fix shadowing `AttributeError` during import.
- Closes #719 
- Relevant quote: 
> The unexpected "does not exist" error is raised during pytest's plugin discovery's command line parsing. This suggests to me two solutions.
>
> * Rearchitecting pytest to honor --pythonpath before its plugin discovery (sounds difficult to change the upstream project)
> * Defer *this* project's module import until *after* pytest honors --pythonpath (sounds easier)
> 
> I'm looking into the latter.
=> fix: defer snapshot default extension import

src/syrupy/extensions/single_file.py, tests/integration/test_single_file_multiple_extensions.py
Fixes regression from https://github.com/tophat/syrupy/pull/710
Closes #717, closes #752
=> fix: incorrect marking of TestClass.test_method as unused, close #717

src/syrupy/__init__.py, tests/integration/test_pytest_extension.py
Waits until there's a report to be printed before adding to the terminal output
- Closes #534, Hide empty snapshot report
Manual testing 👇🏾 
```sh
$ inv test -t 'notestsmatchesthis'
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.11.4, pytest-7.4.0, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /workspaces/syrupy
configfile: pyproject.toml
plugins: syrupy-4.0.4, xdist-3.3.1, benchmark-4.0.0
collected 250 items / 250 deselected / 0 selected …
```
=> fix: hide empty snapshot report

src/syrupy/assertion.py, src/syrupy/location.py, src/syrupy/report.py, tests/integration/test_xfail.py, tests/syrupy/extensions/amber/test_amber_snapshot_diff.py
Not handling xpasses here (contributions welcome). If the number of xfails == failures, we omit the failure summary entirely. Otherwise, we print the number of xfailures.
=> fix: improve reporting around xfailed snapshots, close #736

src/syrupy/assertion.py
This PR does a None check here-https://github.com/tophat/syrupy/blob/f4bc8453466af2cfa75cdda1d50d67bc8c4396c3/src/syrupy/assertion.py#L209
This helps me extend the `SingleFileSnapshotExtension` to save snapshots as HDF files. Please see issue https://github.com/tophat/syrupy/issues/786 to  know more.
Closes https://github.com/tophat/syrupy/issues/786
=> fix: preserve Falsy values in assertion diff function

README.md, src/syrupy/assertion.py, src/syrupy/extensions/amber/serializer.py, src/syrupy/extensions/base.py, src/syrupy/extensions/json/__init__.py, src/syrupy/extensions/single_file.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_filters.ambr, tests/syrupy/extensions/amber/test_amber_filters.py, tests/syrupy/extensions/json/__snapshots__/test_json_filters/test_include_simple.1.json, tests/syrupy/extensions/json/__snapshots__/test_json_filters/test_include_simple.json, tests/syrupy/extensions/json/test_json_filters.py
Adds a basic "include" so we don't have to negate "exclude".
=> feat: add include option to snapshots, similar to exclude

src/syrupy/extensions/amber/serializer.py, src/syrupy/extensions/json/__init__.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_serializer.ambr, tests/syrupy/extensions/amber/test_amber_serializer.py, tests/syrupy/extensions/json/__snapshots__/test_json_serializer/test_function_in_file.json, tests/syrupy/extensions/json/__snapshots__/test_json_serializer/test_function_local.json, tests/syrupy/extensions/json/test_json_serializer.py
* add FunctionType serialization in amber and json extensions
* add tests
add FunctionType serialization in amber and json extensions
- Closes #808 , More generic serialization of function types
I used inspect as I didn't want to re-invent the wheel. Is this satisfactory?
Also of minor concern - this changes the format of existing FunctionType serialization. I don't think this realistically causes a problem as the prior serialization would change every time it ran anyway.
=> feat(serializer): add support for FunctionType serialization

README.md
I was checking out this library and almost bailed after seeing the badge, but syrupy actually does support pytest v8, this is also highlighted in the table in the README
=> chore: updated pytest badge to include v8 in README

src/syrupy/__init__.py, src/syrupy/report.py, src/syrupy/session.py, tests/integration/test_snapshot_skipped.py
This PR tracks the skipped tests and don't mark a snapshot as unused if the corresponding test is skipped.
- Closes #787 
- Closes #842
No comments.
=> fix: ignore unused snapshots for skipped test

poetry.lock, pyproject.toml
=> fix: relax python version constraint, remove upperbound

README.md, src/syrupy/__init__.py, src/syrupy/patches/pycharm_diff.py, tests/integration/test_pycharm_patch.py
(Only relevant for Pycharm users) If the flag is passed, Syrupy will import and extend Pycharm's default diff script to provide more meaning full diffs when viewing snapshots mismatches in Pycharm's diff viewer
When running snapshots tests in Pycharm (in fact, when running tests in general in Pycharm), it has this cool feature where you can see the difference between the `expected` and the `actual` objects in a diff viewer:
```python
def test_example():
expected = {
"a": 1,
"b": 2,
"c": 3,
}
actual = {
"a": 1,
"b": 2,
"c": 5,
}
assert actual== expected
```
After running `test_example`, and looking at Pycharm's console, we can see a link:
By clicking the `<Click to see difference>` link we can easily see the difference and know what the problem was:
However, lets run some snapshot tests …
=> feat: Added a new CLI flag: --snapshot-patch-pycharm-diff

src/syrupy/session.py
Closes #879 
TODO: We likely need a test that leverages pytest-rerunfailures directly. Maybe we should introduce a set of e2e tests with a number of different plugins and merge test coverage.
=> fix: pytest-rerunfailures compatibility

README.md
=> chore: add link to inline-snapshots

src/syrupy/utils.py, tests/integration/test_snapshot_outside_directory.py, tests/syrupy/test_utils.py
This PR aims to allow setting the dirname to something else than `__snapshots__` while maintaining the functionality of a failing test suite when snapshots are unused.
- Closes #868, Where overwriting a dirname causes a test suite not to fail.
I think I changed the `test_walk_dir_skips_non_snapshot_path` test in a wrong way, but since the function this is testing (`walk_snapshot_dir`) is always called in context, this isn't a real use case afaict
=> fix: allow snapshot dir to be different

poetry.lock, pyproject.toml, src/syrupy/extensions/amber/__init__.py, tasks/lint.py
=> ci: replace isort with ruff

src/syrupy/assertion.py, src/syrupy/extensions/base.py, src/syrupy/report.py
SSIA, based on https://docs.astral.sh/ruff/rules/quoted-annotation/
=> chore: remove unnecessary quotes in type annotations

tests/integration/test_custom_comparator.py, tests/integration/test_pycharm_patch.py, tests/integration/test_pytest_extension.py, tests/integration/test_single_file_multiple_extensions.py, tests/integration/test_snapshot_option_extension.py, tests/integration/test_snapshot_option_extension_pythonpath.py, tests/integration/test_snapshot_option_include_details.py, tests/integration/test_snapshot_option_name.py, tests/integration/test_snapshot_option_update.py, tests/integration/test_snapshot_option_warn_unused.py, tests/integration/test_snapshot_outside_directory.py, tests/integration/test_snapshot_similar_names_default.py, tests/integration/test_snapshot_similar_names_file_extension.py, tests/integration/test_snapshot_use_extension.py, tests/integration/test_xfail.py
This was spotted when trying to enforce pyupgrade rules in ruff, and rule UP034 was causing issues: https://docs.astral.sh/ruff/rules/extraneous-parentheses/
Sometimes the first argument was a tuple `stdout.re_match_lines(("a","b"))`, sometimes it was a raw string `stdout.re_match_lines("a")`, and other times it was a bracketed raw string `stdout.re_match_lines(("a"))`
Instead of simply converting the bracketed raw string into non-bracketed raw strings, I think it makes better sense to convert all the raw strings to tuples, as `result.stdout.re_match_lines` is supposed to have a `Sequence[str]` as first argument:
```python
def re_match_lines(
self, lines2: Sequence[str], *, consecutive: bool = False
) -> None:
```
This is not picked up by `mypy` as strings are also a sequence of …
=> chore: use tuple in stdout.re_match_lines

pyproject.toml, src/syrupy/extensions/amber/__init__.py, src/syrupy/extensions/amber/serializer.py, src/syrupy/report.py
SSIA, see https://docs.astral.sh/ruff/rules/#pyupgrade-up
Needs:
=> ci: enable pyupgrade rules in ruff

README.md, src/syrupy/__init__.py, src/syrupy/assertion.py, tests/integration/test_snapshot_option_diff_mode.py, tests/syrupy/__snapshots__/test_diff_mode.ambr, tests/syrupy/test_diff_mode.py
For extremely large snapshot files, the diff algorithm is not very efficient. Until the algorithm can be modified to work with large files, there is now a --snapshot-diff-mode=disabled flag that can be specified to disable diffing on snapshot assertion failures.
- Closes #581
=> feat: add option to disable diffing

src/syrupy/assertion.py, src/syrupy/location.py, src/syrupy/session.py, tests/integration/test_snapshot_diff.py
This PR fixes `assert ... == snapshot(diff=...)` mode to work better in two scenarios:
- Adding two snapshots at the same time (i.e. not already "on disk"), where the second snapshot is a diff from the first
- Changing the base data of a diff'd snapshot
In particular, it seems like the nice performance optimisation of #606, meant the "recalling" used for diffing wasn't finding newly created or updated data, and instead just reading whatever snapshot is available on disk.
This PR resolves the problem by having the recalling managed via the `SnapshotSession`, which can thus check its write queue before reading disk.
- Closes #926 
=> fix: check current session's pending-write queue when recalling snapshots (e.g. diffing)

README.md, src/syrupy/__init__.py, src/syrupy/extensions/base.py, src/syrupy/report.py, src/syrupy/session.py, src/syrupy/utils.py, tests/integration/test_snapshot_option_ignore_file_extensions.py, tests/syrupy/test_utils.py
=> feat: add --snapshot-ignore-file-extensions argument to support DVC

.gitignore, .vscode/extensions.json, .vscode/settings.json, src/syrupy/extensions/amber/serializer.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_newlines.ambr, tests/syrupy/extensions/amber/test_amber_newlines.py
BREAKING CHANGE: Trailing newlines are now preserved in amber serialization. This mostly affects serialization of custom repr implementations.
Closes #925
=> fix(serializer): preserve trailing newlines in ambr serialization

README.md, src/syrupy/extensions/single_file.py, tests/integration/test_invalid_bytes_single_file.py
Improves docs + error message.
Closes #749
=> fix(serializer): raise TypeError when serializing non-byte like object in binary mode

README.md, src/syrupy/matchers.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_matchers.ambr, tests/syrupy/extensions/amber/test_amber_matchers.py
=> feat: add compose_matchers utility for composing 1 or more matchers

src/syrupy/__init__.py
This PR reduces unnecessary calls to `os.environ.update` (via `env_context`) in order to reduce the probability of a segmentation fault caused by a race with `getenv` in another thread as described by https://github.com/syrupy-project/syrupy/issues/955
- The single related issue I'm aware of is https://github.com/syrupy-project/syrupy/issues/955 and:
- this PR should significantly mitigate that issue
- however there are still cases in which `os.environ` is modified (when `assert` compares 2 `SnapshotAssertion` instances and `--snapshot-no-colors` is enabled) so I'm not sure this PR should be marked as one taht "fixes" that issue
- a more full solution may be to avoid setting the env at all if it's possible to replace this with use of `contextvars` instead?
Applying this patch locally …
=> Avoid unnecessary env updates to reduce chances of segfault

README.md, src/syrupy/extensions/single_file.py, tests/syrupy/extensions/__snapshots__/test_amber_single_file/test_amber_single_file.1.ambr, tests/syrupy/extensions/__snapshots__/test_amber_single_file/test_amber_single_file.2.ambr, tests/syrupy/extensions/__snapshots__/test_amber_single_file/test_amber_single_file.ambr, tests/syrupy/extensions/test_amber_single_file.py
=> feat: add SingleFileAmberSnapshotExtension as a single-file variant of the default amber extension

src/syrupy/location.py, src/syrupy/report.py, src/syrupy/session.py, tests/integration/test_snapshot_option_update.py, tests/syrupy/test_location.py
This PR fixes a bug where the snapshots of deselected parametrized tests are wrongly marked as unused.
- Closes #918.
=> fix: snapshots of deselected parametrized tests wrongly marked as unused

.gitignore, .vscode/extensions.json, .vscode/settings.json, src/syrupy/extensions/amber/serializer.py, tests/syrupy/extensions/amber/__snapshots__/test_amber_newlines.ambr, tests/syrupy/extensions/amber/test_amber_newlines.py
Trailing newlines are now preserved in amber serialization. This mostly affects serialization of custom repr implementations.
Related:
- #925 
- #964
Pulling this out of v5 into v4. Considering the behaviour is somewhat broken, I'm not considering this a breaking change.
=> fix(serializer): preserve trailing newlines in ambr serialization (#950)

src/syrupy/__init__.py
This PR prevents pytest_terminal_summary from executing in pytest-xdist worker processes.
I have seen this cause workers to use very high CPU (100% of a core or close) and cause a significant delay at the end of test runs (about 5 seconds).
I cannot see any reason why xdist worker should need to run the terminal summary, so simply preventing execution seems to be a sensible solution. Of course I may be wrong about this.
All tests appear to still pass. It is not obvious to me how to add a test for this change, but I do not think it is really necessary.
None.
- [ n/a] This PR has sufficient documentation.
- [ x] This PR title satisfies semantic [convention](https://www.conventionalcommits.org/en/v1.0.0/#summary).
=> fix: Block terminal summary for xdist workers.

src/syrupy/__init__.py
When using `syrupy` with [pytest-clarity](https://github.com/darrenburns/pytest-clarity/) the `pytest_assertrepr_compare` is called from `pytest-clarity`. This PR ensure `syrupy`'s `pytest_assertrepr_compare` is called first which gives it the ability to handle `SnapshotAssertion` before any other plugin. The code already does an early exit if the `left` or `right` value(s) are not `SnapshotAssertion` and automatically falling back to any other plugin that implements `pytest_assertrepr_compare`.
N/A
=> fix: ensure `syrupy`'s `pytest_assertrepr_compare` hook is called first.
