- .githooks.ini
- dev-requirements.in
- dev-requirements.txt
- script/bootstrap
- src/syrupy/plugins/image/__init__.py
- src/syrupy/plugins/image/io.py
- src/syrupy/session.py
- tasks.py
Slight code changes needs to make it work
Also adds precommit linting
- `inv lint`
- `inv lint --fix`
> chore: type check with mypy in lint task

- .github/workflows/pythonapp.yml
- README.md
- setup.py
- tasks.py
Enables release on tagged builds
> ci: enable deploy

- src/syrupy/assertion.py
- tests/test_snapshots.py
> fix: assert match should raise assertion

- src/syrupy/session.py
Partially addresses #19 
See STR
- Sessions needs to be refactor to better track status
> fix: do not delete partially written snapshot file

- dev-requirements.in
- dev-requirements.txt
- mypy.ini
- pyproject.toml
- setup.py
- src/syrupy/__init__.py
- src/syrupy/assertion.py
- src/syrupy/location.py
- src/syrupy/serializers/__init__.py
- src/syrupy/serializers/base.py
- src/syrupy/serializers/raw_single.py
- src/syrupy/serializers/yaml.py
- src/syrupy/session.py
- src/syrupy/types.py
- stubs/pytest.pyi
- tasks.py
- tests/test_image_plugin.py
- tests/test_snapshots.py
Sort imports as part of formatting and reducing diff size
1. Move `mypy.ini` into pyproject.toml once python/mypy#5205 is resolved
> chore: sort imports

- .github/workflows/pythonapp.yml
- README.md
- dev-requirements.in
- dev-requirements.txt
- tasks.py
Sets up code coverage reporting in prep for #23
> ci: set up coverage

- README.md
> docs: add Python version badge

- .flake8
- dev-requirements.in
- dev-requirements.txt
- pyproject.toml
- setup.py
- src/syrupy/assertion.py
- src/syrupy/serializers/base.py
- src/syrupy/serializers/raw_single.py
- src/syrupy/serializers/yaml.py
- src/syrupy/session.py
- tasks.py
> chore: add flake8 ci and precommit checks

- README.md
License badge is not working b/c https://github.com/tophat/syrupy/issues/58
> docs: restructure badges

- src/syrupy/__init__.py
- src/syrupy/serializers/base.py
- src/syrupy/serializers/raw_single.py
- src/syrupy/serializers/yaml.py
- src/syrupy/session.py
- tests/test_integration.py
- tests/test_plugin_custom.py
> fix: only run updates on selected test nodes

- LICENSE
- MANIFEST.in
- README.md
- setup.py
> chore: surface license

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- tasks.py
Document contributing guide
- Closes #56 
> docs: add contributing guide

- requirements.in
- requirements.txt
- src/syrupy/serializers/amber.py
- tests/test_amber_data_serializer.py
Adds:
- https://github.com/adamchainz/flake8-comprehensions
- https://github.com/PyCQA/flake8-bugbear
- https://github.com/gforcada/flake8-builtins
The comprehension rule provides a minuscule performance benefit, however it ultimately brings us closer to consistently using "one pattern" when two are available (consistent code).
> chore: add flake8 plugins, comprehension, bugbear, builtins

- requirements.in
- requirements.txt
- src/syrupy/__init__.py
- src/syrupy/assertion.py
- src/syrupy/report.py
- src/syrupy/serializers/image.py
- src/syrupy/serializers/raw_single.py
- tests/__snapshots__/test_amber_serializer.ambr
- tests/test_amber_serializer.py
- tests/test_raw_single_serializer.py
Use `gettext` anywhere we show information to the syrupy plugin user
N/A
- Changes made by running `inv requirements`
> fix: get text everything

- src/syrupy/data.py
- src/syrupy/report.py
- src/syrupy/serializers/amber.py
- src/syrupy/serializers/base.py
- src/syrupy/serializers/raw_single.py
- src/syrupy/session.py
- tests/test_raw_single_serializer.py
Minor refactor to clarify snapshot data structures. Prep for v1.
N/A
> refactor: snapshots should know their own names

- src/syrupy/assertion.py
- src/syrupy/report.py
- src/syrupy/serializers/amber.py
- src/syrupy/serializers/base.py
- src/syrupy/serializers/raw_single.py
- src/syrupy/session.py
- tests/test_custom_serializer.py
Assertion should have no business with discovering snapshots
N/A
> refactor: move discover snapshot out of assertion

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Updates changelog in prep for v0.1.0 release.
> docs: v0.1.0 changelog

- README.md
- tests/examples/__snapshots__/test_custom_object_repr.ambr
- tests/examples/test_custom_object_repr.py
Adds documentation for custom object snapshotting
- Closes #71 
> docs: custom object snapshot

- CHANGELOG.md
Prepare v0.3.0 for release
N/A
> chore: update changelog and prep v0.3.0

- CHANGELOG.md
Prepares changelog for 0.3.1 release.
> docs: v0.3.1 changelog

- README.md
> docs: hyperlink status badge

- dev_requirements.txt
- test_requirements.txt
Updates some dev and test dependencies.
> chore: update dev and test dependencies

- CHANGELOG.md
- src/syrupy/extensions/amber.py
```sh
collected 75 items / 74 deselected / 1 selected
tests/test_extension_amber.py .                                                                                                                                                                    [100%]["'parameterized nested class method x'"]
["'parameterized nested class method y'"]
["'parameterized nested class method z'"]
["'this is in a test class'"]
["'a'"]
["'b'"]
["'c'"]
['False']
['True']
["<class 'CustomClass'> {\n", '  a=1,\n', "  b='2',\n", "  c=<class 'list'> [\n", '    1,\n', '    2,\n', '    3,\n', '    ...,\n', '  ],\n', "  d=<class 'dict'> {\n", "    'a': 1,\n", "    'b': 2,\n", "    'c': 3,\n", "    'd': ...,\n", '  },\n', "  x=<class 'CustomClass'> {\n", '    a=1,\n', "    b='2',\n", "    c=<class 'list'> [\n", ' …
```
> fix: remove rogue print statement

- CHANGELOG.md
- src/syrupy/__init__.py
- src/syrupy/assertion.py
- src/syrupy/data.py
- src/syrupy/exceptions.py
- src/syrupy/extensions/__init__.py
- src/syrupy/location.py
- src/syrupy/report.py
- src/syrupy/session.py
- src/syrupy/utils.py
- tests/test_integration_default.py
e.g. This PR refactors the X submodule, applying Y's algorithm to improve Z by K percent.
- Closes #0, a short description of the linked issue.
> wip: resolve #132 conflicts

- README.md
- tests/test_integration_default.py
Add documentation for `--snapshot-default-extension` option
> docs: add snapshot extension option and defaults

- CHANGELOG.md
> Release v0.3.3

- src/syrupy/__init__.py
- src/syrupy/constants.py
- src/syrupy/data.py
- src/syrupy/extensions/amber.py
- src/syrupy/extensions/base.py
- src/syrupy/terminal.py
- tests/__snapshots__/test_integration_default.ambr
e.g. This PR refactors the X submodule, applying Y's algorithm to improve Z by K percent.
- Closes #0, a short description of the linked issue.
> wip: rewrite assertion diff report

- .github/workflows/release.yml
- .releaserc.js
Uses [github semantic-release action](https://github.com/marketplace/actions/action-for-semantic-release) powered by the [npm semantic-release package](https://github.com/semantic-release/semantic-release) to
**On `master` branch**
1. analyse commit history since last version to determine new version
1. update changelog with release notes
1. commit changelog to git and push to remote
1. push new version tag to github (_**This will trigger release to pypi**_)
1. create release on github from version tag with notes
- Relates to #43 
> Automate semantic releases

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
- .releaserc.js
- CHANGELOG.md
Enable semantic release
- Closes #43
> ci: enable semantic release

- tasks.py
Do not fail release if existing file
N/A
> ci: do not fail release if existing file

- README.md
Add pytest 5.1.0 badge to readme
> docs: add pytest 5.1.0 badge

- script/demo
Update usage gif in readme to reflect latest assertion diff reporting
- Closes #154 
- Adds applescript to easily rerun the demo --> `./scripts/demo`
> docs: update usage demo gif

- .github/workflows/auto-approve.yml
Auto approve dependabot actions
> ci: auto approve dependabot

- dev_requirements.txt
- test_requirements.txt
> build(deps) bump all dev and test dependencies

- script/bootstrap
From https://github.com/tophat/syrupy/pull/213, by @sloria
> chore: remove unnecessary shebang from script

- setup.py
PR: https://github.com/tophat/syrupy/pull/239
> Update setup.py, so that it allows for any Python 3.6+ version to be used

- .github/PULL_REQUEST_TEMPLATE.md
> docs: update pr template

- conftest.py
- pyproject.toml
- pytest.ini
- stubs/pytest.pyi
Moves pytest config file into the pyproject file
> chore: move pytest.ini into pyproject.toml

- dev_requirements.txt
- setup.py
- tests/test_integration_pytest_extension.py
> chore: Mark compatibility with pytest v6.x

- src/syrupy/extensions/amber/serializer.py
- tests/__snapshots__/test_extension_amber.ambr
- tests/test_extension_amber.py
Will cause a breaking snapshot change.
> fix: pass indent to multiline open tag, close #332

- README.md
See: https://github.com/tophat/getting-started/blob/master/scorecard.md.
Will wait until we release v1 before upgrading to "Critical".
> docs(readme): update project maturity to stable

- README.md
Force a patch release for attrs dependency
> fix: support attrs <21.0.0

- .github/workflows/pythonapp.yml
- min_requirements.txt
- script/bootstrap
- setup.py
- src/syrupy/assertion.py
- src/syrupy/extensions/base.py
- tasks.py
- tests/test_integration_pytest_extension.py
Refactors CI to perform one test run using the minimum supported dependencies.
> build: test min install requires versions

- .releaserc.js
- README.md
- setup.py
BREAKING CHANGE: Release v1.0.0
> feat: update development status to stable

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- README.md
Fixes some documentation.
- Closes #424, add question type issue.
> docs: fix links, add question issue, close #424

- .github/workflows/cicd.yml
- tasks.py
I believe this should run CI for pull requests based with branches in forked repos.
- Closes #434
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories-2
> chore: run ci on pull request target, close #434

- .github/workflows/cicd.yml
- dev_requirements.txt
- min_requirements.constraints
- tasks.py
chore: rename min constraints to hide from dependabot
> chore: update dev dependencies

- .github/workflows/cicd.yml
- setup.py
Not sure what broke recently, possibly with a setuptools_scm update. This should at least ensure scm distance is 0.
> fix: force release

- .github/workflows/cicd.yml
- tasks.py
https://github.com/tophat/syrupy/issues/497
> chore: only publish to test pypi on dry run, close #497

- README.md
Adds documentation on additional ways to customize object representation.
- https://github.com/tophat/syrupy/issues/502#issuecomment-851060896
* We should think about breaking the readme into doc files covering different use cases, we already have code examples but they are not easily discoverable.
> docs: add custom object serialized attribute configuration

- .github/workflows/cicd.yml
- benchmarks/__init__.py
Fixes benchmark status reporting
> ci: fix benchmarks status reporting

- .github/workflows/cicd.yml
Speed up PR builds from [`~5m`](https://github.com/tophat/syrupy/actions/runs/901432129) to `~3m` by not waiting for tests to run pr only specific dry run checks
> ci: fast follow review dry run build

- .github/actions/detect-env/action.yml
- .github/actions/detect-python/action.yml
- .github/workflows/cicd.yml
- benchmarks/__init__.py
Fixes benchmark reporting on master
> ci: fix benchmark reporting on master

- .github/codecov.sh
- .github/workflows/cicd.yml
- .gitignore
- codecov.yml
- dev_requirements.txt
- setup.py
- tasks/test.py
> chore: fix coverage reporting

- src/syrupy/report.py
> perf: discover snapshots once per file rather than per assertion

- src/syrupy/session.py
Originally tried memoizing the discover_snapshot method itself, but the time spent seems to be the loop and dict merging rather than the IO
Related: #539
> perf: cache session snapshot extension discovery

- .github/workflows/next.yml
Attempt at fixing the failing master next build https://github.com/tophat/syrupy/runs/4022855733?check_suite_focus=true
> ci: fix next version push

- pyproject.toml
> fix: use more expressive glob when building whl

- .github/codecov.sh
- .github/workflows/cicd.yml
- codecov.yml
- poetry.lock
- pyproject.toml
- tasks/test.py
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259/4
> chore: remove codecov package

- poetry.lock
- pyproject.toml
- src/syrupy/extensions/base.py
- tasks/benchmark.py
- tasks/build.py
- tasks/lint.py
- tasks/test.py
> ci: add ruff to lint process

- poetry.lock
- pyproject.toml
- src/syrupy/patches/pycharm_diff.py
- tasks/lint.py
> ci: replace black with ruff formatter

- .github/workflows/release.yaml
...will create a ticket to track this
> chore: remove prelease, as it's incompatibile with pypi versioning

- README.md
Removed note about main branch pointing to v5 pre-release.
e.g. This PR refactors the X submodule, applying Y's algorithm to improve Z by K percent.
- Closes #0, a short description of the linked issue.
> Update README to remove outdated branch note
